# Generated by Django 3.2.13 on 2023-12-22 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_auto_20231220_2242'),
        ('users', '0002_user_shop_adress'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_shop',
            unique_together={('user', 'shop', 'adress')},
        ),
    ]
